version: 2.1

parameters:
  pull_request:
    type: boolean
    default: false

orbs:
  node: circleci/node@4.7.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Test Application Develop
      # - run:
      #     command: npm run build
      #     name: Build App
      
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
          
workflows:
  my_workflow:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - build_and_test
#           filters:
#             branches:
#               only:
#                 - master
